/**
 * Intelligence module — public barrel.
 *
 * Implements Phase 1 of the Unified Intelligence Layer: canonical signal
 * ingestion, entity-link resolution, unified timeline, shared semantic
 * metrics, and data-quality/freshness indicators.
 */
export const MODULE_NAME = "intelligence" as const;

export type {
  SignalRecord,
  EntityLinkRecord,
  DataQualityIssueRecord,
  MetricDefinitionRecord,
  MetricSnapshotRecord,
  TimelineEvent,
  CustomerIntelligenceSummary,
  BusinessInsightRecord,
  BusinessInsightEvidence,
  RecommendationRecord,
  ActionPlanRecord,
  OutcomeRecord,
  GoalRecord,
  PredictionRecord,
  HypothesisRecord,
  BusinessLearningRecord,
  CompetitorInsightRecord,
  PortfolioSnapshotRecord,
  SystemMetricRecord,
  JourneyStage,
  ConfidenceLevel,
  LinkStatus,
  DataQualitySeverity,
  DataQualityStatus,
  MetricSnapshotStatus,
  InsightType,
  InsightSeverity,
  InsightStatus,
  RecommendationStatus,
  ActionPlanStatus,
  OutcomeStatus,
  GoalStatus,
  PredictionType,
  PredictionStatus,
  HypothesisStatus,
  RiskTier,
  ProductScoreRecord,
  MarketingMemoryRecord,
  DailyBriefRecord,
  DailyBriefSection,
  ConversationPattern,
  TrendingHashtag,
  CompetitorChange,
  BusinessObjective,
  DailyActionRecord,
  DailyActionStatus,
  ActionOutcomeRecord,
  ActionOutcomeStatus,
  JourneyRecord,
  JourneyStepRecord,
  JourneyStepType,
  JourneyOutcome,
} from "./domain/types";

export { canExecuteRecommendation, isRecommendationExpired } from "./domain/recommendation";
export type { ExecutableCheck } from "./domain/recommendation";

export type { IngestSignalInput } from "./application/signal-ingestion";
export type { TimelineQuery } from "./application/timeline";
export type { BusinessBrainContext, BusinessBrainContextService, SourceCitation, CitationSource } from "./application/business-brain-context";
export type { DailyActionService } from "./application/daily-action";
export type { ActionOutcomeService } from "./application/action-outcome";
export type { JourneyService } from "./application/journey";
export type {
  InboxNextBestAction,
  OrdersNextBestAction,
  CustomerNextBestAction,
  ContentNextBestAction,
  CampaignsNextBestAction,
  BrandDealNextBestAction,
  CompetitorNextBestAction,
} from "./application/next-best-action";

export {
  signalIngestionService,
  entityResolutionService,
  timelineService,
  metricService,
  dataQualityService,
  customerSummaryService,
  detectionService,
  diagnosisService,
  intelligenceFeedService,
  recommendationService,
  recommendationLifecycleService,
  businessBrainContextService,
  dailyActionService,
  actionOutcomeService,
  journeyService,
  actionPlanService,
  decisionPolicyService,
  outcomeService,
  businessLearningService,
  goalService,
  predictionService,
  hypothesisService,
  portfolioService,
  competitorIntelligenceService,
  costLatencyMonitor,
  nextBestActionService,
  proactiveNotificationService,
  goalAutomationService,
  kpiService,
  aiGovernanceService,
  qualityAssuranceService,
  rolloutService,
  riskMitigationRegistry,
} from "./infrastructure/container";

export {
  getCustomerTimelineAction,
  getCustomerIntelligenceAction,
  getDataQualityIssuesAction,
  getMetricAction,
  getIntelligenceFeedAction,
  dismissInsightAction,
  getRecommendationsAction,
  approveRecommendationAction,
  executeActionPlanAction,
  dismissRecommendationAction,
  getGoalsAction,
  createGoalAction,
  getPredictionsAction,
  getHypothesesAction,
  getBusinessLearningAction,
  getAgencyPortfolioAction,
  getCompetitorIntelligenceAction,
  getSystemHealthAction,
  getInboxNextBestActionAction,
  getOrdersNextBestActionAction,
  getCrmNextBestActionAction,
  getContentNextBestActionAction,
  getCampaignsNextBestActionAction,
  getBrandDealsNextBestActionAction,
  getCompetitorNextBestActionAction,
  getStoreMetricsAction,
  getAutomationTemplatesAction,
  createGoalAutomationAction,
  getWorkspaceKpisAction,
  formatAiResponseAction,
  validateToolCallAction,
  validateWorkflowAction,
  runQualityChecksAction,
  getRolloutGatesAction,
  setRolloutGateAction,
  getRiskMitigationsAction,
  getOperatingModelAction,
  getRiskMatrixAction,
  getUnifiedContextAction,
  getKnowledgeGraphAction,
  getFeatureProfileAction,
  createGoalPlanWorkflowAction,
  testGoalPlanWorkflowAction,
  launchGoalPlanWorkflowAction,
  getLearningEvidenceAction,
  getModelOpsAction,
  evaluatePredictionPriorityAction,
  submitIntelligenceFeedbackAction,
  getIntelligenceFeedbackKpisAction,
  getInsightDrillDownAction,
  dismissInsightWithReasonAction,
  evaluateChartAcceptanceAction,
  mergeEntityAction,
  splitEntityAction,
  getMarketingMemoryAction,
  getRecommendationConflictsAction,
  refreshReadModelsAction,
  getTodayActionsAction,
  completeDailyActionAction,
  skipDailyActionAction,
  getJourneysAction,
  getJourneyAction,
  getBusinessBrainContextAction,
  getRecommendationDetailAction,
} from "./presentation/actions";

export { RecommendationConflictCard } from "./presentation/components/recommendation-conflict-card";

export type { IntelligenceActionState, MarketingMemoryState } from "./presentation/actions";
export type { QualityReport, QualityCheck } from "./application/quality-assurance";
export type { RolloutGate, RolloutMode } from "./application/rollout";
export type { RiskMitigation } from "./application/risk-mitigations";
export {
  operatingModelService,
  updateMarketingMemory,
  generateDailyBrief,
  generateMarketingInsightsFromMemory,
  unifiedContextService,
  knowledgeGraphService,
  featureService,
  goalPlanGenerationService,
  learningEvidenceService,
  modelOpsService,
  predictionPrioritizationService,
  intelligenceFeedbackService,
  intelligenceFeedInteractionService,
  chartAcceptanceService,
  dataQualityGateService,
} from "./infrastructure/container";
export { runWeek4ThinSlice } from "./infrastructure/thin-slice";
export type { OperatingModel, OperatingModelService, Story, RiskTierRow, SuccessCriterion, Squad, Milestone, IntegrationHealth, EvaluationCase, ThinSliceReview } from "./application/operating-model";
export type { ThinSliceResult } from "./infrastructure/thin-slice";
export type {
  UnifiedContext,
  KnowledgeGraphResult,
  CustomerFeatures,
  ProductFeatures,
  ContentFeatures,
  CampaignFeatures,
  BusinessFeatures,
  GoalPlan,
  LearningEvidence,
  ModelOpsState,
  ModelVersion,
  FeedbackRating,
  PredictionPrioritizationInput,
  Chart,
  DataQualityGateResult,
  DrillDown,
} from "./application/validation-driven";
